openapi: "3.1.0"
info:
  title: "dir-file-cataloger"    # アプリケーション名
  version: "0.9.7"                       # バージョン
  description: "Collects and catalogs general metadata from all accessible directories and files, independent of the specific filesystem."
  termsOfService: "https://example.com/terms/"
  contact:
    name: "Takashi Sasaki"
    url: "https://x.com/TakashiSasaki"
    email: "takashi316@gmail.com"
  license:
    name: "MIT License"
    url: "https://opensource.org/licenses/MIT"
  x-filename: "app.yaml"
  x-application-uuidv4: 
    value: 5a8ae9ed-7872-4eca-bf74-660f3ed413eb
    description: "Unique identifier for this application, used to distinguish it from other applications."

servers:
  - url: "https://api.example.com/v1"
    description: "Production server"
components:
  schemas:
    FileMetadata:
      type: object
      description: |
        Metadata for files and directories. The properties `Filename`, `Size`, `Date Modified`, 
        `Date Created`, and `Attributes` are used in the Everything file search software, 
        which is distributed at https://www.voidtools.com/. When the catalog is converted 
        to CSV format, these property names are retained as headers to maintain consistency.
      properties:
        Filename:
          type: string
          description: "The full path or name of the file or directory."
          x-csv-header: "Filename"
        Size:
          type: integer
          format: int64
          description: "The size of the file or directory in bytes."
          x-csv-header: "Size"
        DateModified:
          type: string
          format: date-time
          description: |
            The date and time when the file or directory was last modified. 
            This timestamp uses the NTFS format as used by Windows file systems:
            - **Epoch**: January 1, 1601 (UTC).
            - **Resolution**: 100 nanoseconds.
            - **Time Zone**: UTC, without any time zone offsets or daylight saving adjustments.
          x-csv-header: "Date Modified"
        DateCreated:
          type: string
          format: date-time
          description: |
            The date and time when the file or directory was created. Uses NTFS timestamp format.
          x-csv-header: "Date Created"
        Attributes:
          type: integer
          description: "File or directory attributes represented as a bitmask."
          x-csv-header: "Attributes"
      required:
        - Filename
        - Size
        - DateModified
        - DateCreated
        - Attributes
paths:
  /catalog:
    get:
      summary: "Initiate a cataloging operation of the filesystem"
      operationId: "initiateCataloging"
      tags:
        - "Catalog"
      responses:
        '200':
          description: "Cataloging initiated successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cataloging initiated successfully"
